# Generated by Django 4.0.6 on 2022-07-19 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Yarn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=100)),
                ('weight', models.CharField(max_length=100)),
                ('brand', models.TextField(max_length=250)),
            ],
        ),
    ]
