# Generated by Django 4.0.6 on 2022-07-20 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(max_length=100)),
                ('content', models.CharField(max_length=100)),
                ('yarn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.yarn')),
            ],
        ),
        migrations.DeleteModel(
            name='Content',
        ),
    ]
